DROP TABLE SPORT_DEADLINE cascade constraints purge;

select * from SPORT_DEADLINE
create table SPORT_DEADLINE(
	REGISTER_ID references MEMBER_INFO(USER_ID),
	APPLY_ID references MEMBER_INFO(USER_ID),
	DEADLINE_NUM NUMBER primary key,
	REGISTER_NUM references SPORT_REGISTER(REGISTER_NUM),
	SPORT_NUM references SPORTS(SPORTS_NUM)
);

select * from SPORT_DEADLINE;
select SPORT_DEADLINE.SPORT_NUM, SPORT_DEADLINE.REGISTER_ID, SPORT_DEADLINE.APPLY_ID, 
		SPORT_REGISTER.MATCH_ADR, SPORT_REGISTER.MATCH_DTL_ADR, SPORT_REGISTER.MATCH_TIME,
		SPORT_REGISTER.MATCH_PRS, SPORT_REGISTER.MATCH_SKL, SPORT_REGISTER.REGISTER_NUM
		FROM SPORT_DEADLINE, SPORT_REGISTER
		WHERE SPORT_DEADLINE.REGISTER_NUM = SPORT_REGISTER.REGISTER_NUM
		AND SPORT_DEADLINE.REGISTER_ID = 'admin111' OR SPORT_DEADLINE.REGISTER_NUM = SPORT_REGISTER.REGISTER_NUM and APPLY_ID = 'admin111';
create sequence dead_seq;


insert into SPORT_DEADLINE(REGISTER_ID, APPLY_ID, DEADLINE_NUM, SPORT_NUM)
values('admin01', 'admin03', dead_seq.nextval, 1);

insert into SPORT_DEADLINE(REGISTER_ID, APPLY_ID, DEADLINE_NUM, SPORT_NUM)
values('admin02', 'admin01', dead_seq.nextval, 2);

insert into SPORT_DEADLINE(REGISTER_ID, APPLY_ID, DEADLINE_NUM, SPORT_NUM)
values('admin03', 'admin02', dead_seq.nextval, 3);


