--회원정보
CREATE TABLE MEMBER_INFO(
USER_ID			 VARCHAR2(60) PRIMARY KEY,	--회원ID
USER_PASS		 VARCHAR2(60) NOT NULL,		--회원비밀번호
USER_NAME		 VARCHAR2(15) NOT NULL,		--회원이름
USER_JUMIN		 VARCHAR2(13) NOT NULL,		--회원주민번호
USER_MOBILE		 VARCHAR2(11) NOT NULL,		--회원전화번호
USER_ADDRESS	 VARCHAR2(300) NOT NULL,	--회원주소
USER_EMAIL		 VARCHAR2(100) NOT NULL,	--회원이메일
USER_HEIGHT		 NUMBER NOT NULL,			--회원신장(키)
USER_PWEIGHT	 NUMBER NOT NULL,			--회원현재몸무게
USER_WWEIGHT	 NUMBER NOT NULL,			--회원목표몸무게
USER_BMI		 NUMBER,					--회원BMI(현재몸무게/(키*키)*10000)
USER_RMR		 NUMBER,					--회원기초대사량
											--(남자:66.47+(13.75*현재몸무게)+(5*키)-(6.75*나이)
											--(여자:655.1+(9.56*현재몸무게)+(1.85*키)-(4.68*나이)
USER_WATER		 VARCHAR2(10),				--회원물섭취량
USER_IMAGE		 VARCHAR2(150),				--회원 프로필
USER_PSPORTS	 VARCHAR2(50)				--선호운동
);

SELECT * FROM MEMBER_INFO;--MEMBER_INFO 조회
delete from MEMBER_INFO where USER_ID='admin';

DROP TABLE MEMBER_INFO CASCADE CONSTRAINTS;--MEMBER_INFO 삭제

INSERT INTO MEMBER_INFO(
USER_ID,USER_PASS,USER_NAME,
USER_JUMIN,USER_MOBILE,USER_ADDRESS,
USER_EMAIL,USER_HEIGHT,USER_PWEIGHT,USER_WWEIGHT,
USER_BMI,USER_RMR,USER_WATER
) VALUES(
'admin',1234,'2조',								--ID, 비밀번호, 이름
9009091234567,01032905515,'사랑시 고백구 행복동',	--주민번호, 전화번호, 주소
'niggo0803@gmail.com',200,100,90,				--이메일, 키, 현재몸무게, 목표몸무게
25,1831.3,1										--BMI, 기초대사량, 물섭취량				
)